import {record} from '@rrweb/record';
import {pickState,pickMessages} from '../src/core/model.js';
(()=>{if(window.__ccReplayRecorder)return;window.__ccReplayRecorder=true;
let stopAll;
window.addEventListener('ccreplay-start',event=>{
 if(stopAll)return;const channel=event.detail.channel;const started=Date.now();const time=()=>Date.now()-started;let batch=[];const push=(kind,data)=>{batch.push({kind,...data});if(batch.length>=100)flush();};const flush=()=>{if(batch.length){window.postMessage({source:'ccreplay',channel,batch},location.origin);batch=[];}};
 const roomId=location.pathname.split('/')[2];let store;let classes=new Set();let roots=[];
 function discover(){
  roots=[];for(const el of [document.querySelector('#root'),...Array.from(document.body.children)].filter(Boolean)){for(const key of Object.keys(el)){if(key.startsWith('__reactContainer$')||key.startsWith('__reactFiber$')){let f=el[key];while(f?.return)f=f.return;roots.push(f?.stateNode?.current||f);}}}
  const visited=new Set();const todo=[...roots];while(todo.length&&visited.size<60000){const f=todo.pop();if(!f||visited.has(f))continue;visited.add(f);const p=f.memoizedProps;const contexts=[];let cx=f.dependencies?.firstContext;while(cx){contexts.push(cx.memoizedValue);cx=cx.next;}
   for(const c of [p?.store,p?.value?.store,...contexts.map(c=>c?.store)])if(c?.getState&&c?.subscribe&&c.getState()?.entities?.rooms)store=c;
   let h=f.memoizedState;let i=0;while(h&&i++<100){const v=h.memoizedState;const candidates=[v?.current,Array.isArray(v)?v[0]:null];for(const c of candidates)if(c?.audioElement instanceof HTMLMediaElement&&Array.isArray(c.constructor?.players))classes.add(c.constructor);h=h.next;}
   if(f.child)todo.push(f.child);if(f.sibling)todo.push(f.sibling);
  }
 }
 discover();
 if(!store){push('warning',{t:0,text:'코코포리아 상태 연결 실패: DOM만 기록됩니다. 토큰·채팅·BGM 상태 기록을 보장할 수 없습니다.'});}
 const assets=new Set();function asset(url){if(!url||assets.has(url)||!/^https?:/.test(url))return;assets.add(url);push('asset',{url});}
 function findAssets(value){if(typeof value==='string'){if(/^https?:\/\//.test(value)&&value.length<10000)asset(value);for(const match of value.matchAll(/url\(["']?(https?:[^)'"\s]+)["']?\)/g))asset(match[1]);}else if(value&&typeof value==='object')for(const [k,v]of Object.entries(value))if(!['text','memo','name'].includes(k))findAssets(v);}
 let lastState='';const lastMessages=new Map();let unsubscribe;function snapshot(){if(!store)return;try{const s=store.getState();const visibleItems={};for(const el of document.querySelectorAll('[data-field-object]')){const img=el.querySelector('img');visibleItems[el.getAttribute('data-field-object')]={imageUrl:img?.currentSrc||img?.src||''};}const frame=pickState(s,roomId,visibleItems);const encoded=JSON.stringify(frame);if(encoded!==lastState){push('frame',{t:lastState?time():0,...frame});lastState=encoded;findAssets(frame);}for(const m of pickMessages(s,roomId,true)){const encoded=JSON.stringify(m);if(lastMessages.get(m.id)!==encoded){lastMessages.set(m.id,encoded);push('message',{t:time(),...m});asset(m.iconUrl);asset(m.imageUrl);}}}catch(e){push('warning',{t:time(),text:e.message});}}
 snapshot();if(store)unsubscribe=store.subscribe(snapshot);let snapshotPending=false;const changes=new MutationObserver(()=>{if(snapshotPending)return;snapshotPending=true;requestAnimationFrame(()=>{snapshotPending=false;snapshot();});});changes.observe(document.querySelector('#root')||document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['src','style','data-field-object']});
 const players=new Map();const nativeAudio=new Set();let nextId=0;const seenAudio=new WeakSet();const cleanup=[];function captureAudio(){const active=new Set();const discovered=[...classes].flatMap(c=>c.players||[]);const known=new Set(discovered.map(p=>p.audioElement));const list=[...discovered,...[...document.querySelectorAll('audio,video'),...nativeAudio].filter(a=>!known.has(a)).map(a=>({audioElement:a}))];for(const player of list){const a=player.audioElement;if(!a||!/^https?:/.test(a.currentSrc||a.src))continue;const key=a;active.add(key);let entry=players.get(key);if(!entry){entry={id:'audio-'+nextId++,last:null,player};players.set(key,entry);}entry.player=player;const url=a.currentSrc||a.src;asset(url);const value={t:time(),id:entry.id,url,position:Number.isFinite(a.currentTime)?a.currentTime:0,paused:a.paused||a.ended,loop:a.loop,volume:a.muted?0:Math.max(0,Math.min(1,player.gainNode?.gain?.value??a.volume)),rate:a.playbackRate};const old=entry.last;const expected=old?old.position+(value.t-old.t)/1000*(old.paused?0:old.rate):0;if(!old||old.url!==url||old.paused!==value.paused||old.loop!==value.loop||old.rate!==value.rate||Math.abs(old.volume-value.volume)>.008||Math.abs(expected-value.position)>.12||value.t-old.t>=5000){push('audio',value);entry.last=value;}
   if(!seenAudio.has(a)){seenAudio.add(a);for(const type of ['playing','pause','seeked','ratechange','volumechange','ended']){const cb=()=>captureAudio();a.addEventListener(type,cb);cleanup.push(()=>a.removeEventListener(type,cb));}}
  }for(const [key,entry]of players){if(!active.has(key)){push('audio',{t:time(),id:entry.id,stopped:true});players.delete(key);}}}
 const restores=[];let discoveryPending=false;for(const name of ['load','play']){const original=HTMLMediaElement.prototype[name];function wrapped(...args){nativeAudio.add(this);captureAudio();if(!discoveryPending){discoveryPending=true;setTimeout(()=>{discoveryPending=false;discover();captureAudio();},0);}return Reflect.apply(original,this,args);}HTMLMediaElement.prototype[name]=wrapped;restores.push(()=>{if(HTMLMediaElement.prototype[name]===wrapped)HTMLMediaElement.prototype[name]=original;});}
 const rrstop=record({emit(e){push('event',{event:e});findAssets(e);},checkoutEveryNms:60000,maskAllInputs:true,recordCanvas:false,inlineStylesheet:true,collectFonts:true,sampling:{mousemove:50,scroll:100},blockSelector:'input[type="password"], [data-ccreplay-ignore]'});
 for(const img of document.images)asset(img.currentSrc||img.src);
 const poll=setInterval(captureAudio,50);const discovery=setInterval(()=>{discover();if(!unsubscribe&&store){unsubscribe=store.subscribe(snapshot);}snapshot();},1500);const flusher=setInterval(flush,250);
 push('meta',{adapter:!!store,startedAt:started,title:document.title,viewport:{width:innerWidth,height:innerHeight}});captureAudio();flush();
 stopAll=()=>{rrstop?.();unsubscribe?.();changes.disconnect();clearInterval(poll);clearInterval(discovery);clearInterval(flusher);restores.forEach(fn=>fn());cleanup.forEach(fn=>fn());snapshot();captureAudio();push('end',{t:time()});flush();stopAll=null;};
 window.addEventListener('pagehide',()=>stopAll?.(),{once:true});
});window.addEventListener('ccreplay-stop',()=>stopAll?.());})();
