import {Replayer} from '@rrweb/replay';
import '@rrweb/replay/dist/style.css';
import './style.css';
import {$,$$,ic,paintIcons,shell} from './shell.js';
import {frameAt,messagesAt,audioAt,timeLabel,escapeHTML as esc,clamp} from './core/model.js';
import {readArchive,makeArchive,downloadBlob,sanitizeEvents} from './core/archive.js';
import {demoRecording,demoSound} from './core/demo.js';
import {AudioEngine} from './core/audio.js';
let current,engine,replayer,time=0,playing=false,speed=1,volume=.7,tab='chat',mode='scene',query='',selected=null,last=0,renderStamp=0,chatStamp=0,frameKey,zoom=1,pan={x:0,y:0};
shell();
const notify=message=>{$('#notice').textContent=message;$('#notice').hidden=!message;};
const url=value=>current?.assets.get(value)||'';
const color=value=>/^#[a-f\d]{3,8}$/i.test(value)?value:'#c4bcab';
function page(name){$('#replay-page').hidden=name!=='replay';$('#record-page').hidden=name!=='record';$('#replay-nav').classList.toggle('active',name==='replay');$('#record-nav').classList.toggle('active',name==='record');if(name==='record')pause();}
function dialog(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').showModal();paintIcons();}
const stats=t=>`<span class="token-stats">${(t.status||[]).map(s=>`<span>${esc(s.label)}<b>${esc(s.value)}<small> / ${esc(s.max)}</small></b></span>`).join('')}</span>`;
function renderScene(force=false){const f=frameAt(current?.data.frames||[],time);if(!f){$('#world').innerHTML='<span class="no-state">장면 상태가 없습니다. 기록 화면을 선택하세요.</span>';return;}if(frameKey===f&&!force)return;frameKey=f;const cell=clamp(f.cellSize,8,200)||24;const width=clamp(f.room.fieldWidth,1,500)*cell,height=clamp(f.room.fieldHeight,1,500)*cell;$('#board').style.backgroundImage=url(f.room.backgroundUrl)?`linear-gradient(#12161c55,#12161c55),url("${url(f.room.backgroundUrl)}")`:'';
 $('#world').innerHTML=`<div class="map-field ${f.room.displayGrid?'grid':''}" style="left:${-Math.floor(f.room.fieldWidth/2)*cell}px;top:${-Math.floor(f.room.fieldHeight/2)*cell}px;width:${width}px;height:${height}px;--cell:${cell*clamp(f.room.gridSize||1,.25,20)}px;background-color:${color(f.room.backgroundColor)}">${url(f.room.foregroundUrl)?`<img class="field-image" src="${url(f.room.foregroundUrl)}" style="object-fit:${f.room.fieldObjectFit==='cover'?'cover':'fill'}" alt="기록된 전경">`:''}</div>${f.items.map(i=>`<button class="board-item" style="left:${clamp(i.x,-1e5,1e5)}px;top:${clamp(i.y,-1e5,1e5)}px;width:${clamp(i.width,.1,500)*cell}px;height:${clamp(i.height,.1,500)*cell}px;z-index:${clamp(i.z,0,500)};transform:rotate(${clamp(i.angle,-3600,3600)}deg)" title="${esc(i.text)}">${url(i.imageUrl)?`<img src="${url(i.imageUrl)}" alt="${esc(i.text||'패널')}">`:`<span>${esc(i.text||'이미지 없음')}</span>`}</button>`).join('')}${f.tokens.map(c=>`<button class="token ${selected===c.id?'selected-token':''}" data-token="${esc(c.id)}" aria-label="${esc(c.name)} 토큰 정보" style="left:${clamp(c.x,-1e5,1e5)}px;top:${clamp(c.y,-1e5,1e5)}px;width:${clamp(c.width,.1,100)*cell}px;height:${clamp(c.height,.1,100)*cell}px;--token-color:${color(c.color)};z-index:${600+clamp(c.z,0,100)}"><span class="token-art" style="transform:rotate(${clamp(c.angle,-3600,3600)}deg)">${url(c.iconUrl)?`<img src="${url(c.iconUrl)}" alt="">`:`<span>${esc((c.name||'?').slice(0,1))}</span>`}</span><span class="token-label">${esc(c.name)}</span></button>`).join('')}`;
 $('#token-count').textContent=f.tokens.length;$('#scene-name').textContent=current.data.demo?(time<45000?'새벽의 플랫폼':'불이 켜진 역무실'):'기록된 장면';$('#scene-hint').textContent=current.data.demo?'체험용 예시 · 토큰을 가리켜 보세요':'드래그로 시점 이동 · 토큰을 가리켜 정보 확인';fitWorld();}
function fitWorld(){const f=frameAt(current?.data.frames||[],time);if(!f)return;const fit=Math.min(($('#board').clientWidth-90)/(f.room.fieldWidth*(f.cellSize||24)),($('#board').clientHeight-100)/(f.room.fieldHeight*(f.cellSize||24)),1.3);$('#world').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${Math.max(.05,fit)*zoom})`;$('#zoom-label').textContent=Math.round(zoom*100)+'%';}
function renderInspector(){if(!current)return;$('#search-wrap').hidden=tab!=='chat';$$('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);b.setAttribute('aria-selected',b.dataset.tab===tab);});const content=$('#inspector-content'),bottom=content.scrollHeight-content.scrollTop-content.clientHeight<60;const all=messagesAt(current.data.messages,current.data.duration);$('#chat-count').textContent=all.length;
 if(tab==='chat'){const list=query?all.filter(m=>(m.text+' '+m.name+' '+m.channelName).toLocaleLowerCase().includes(query.toLocaleLowerCase())):messagesAt(current.data.messages,time);$('#inspector-subtitle').textContent=query?`전체 기록에서 ${list.length}개 검색됨`:'현재 시점까지의 채팅';content.innerHTML=list.length?list.map(m=>`<button class="chat-message" data-message-time="${m.t}"><span class="chat-avatar" style="--avatar:${color(m.color)}">${url(m.iconUrl)?`<img src="${url(m.iconUrl)}" alt="">`:esc((m.name||'?').slice(0,1))}</span><span class="chat-body"><span class="chat-heading"><b style="color:${color(m.color)}">${esc(m.name||'이름 없음')}</b><time>${timeLabel(m.t)}</time></span><span class="chat-channel">${esc(m.channelName||m.channel)}${m.private?' · 비공개':''}${m.edited?' · 수정됨':''}</span><span class="chat-text">${esc(m.text)}</span>${url(m.imageUrl)?`<img class="chat-image" src="${url(m.imageUrl)}" alt="채팅 이미지">`:''}</span></button>`).join(''):`<div class="inspector-empty">${ic('file-text')}<p>${query?'검색 결과가 없습니다.':'이 시점에 표시할 채팅이 없습니다.'}</p></div>`;if(!query&&bottom)content.scrollTop=content.scrollHeight;}
 else{const tokens=frameAt(current.data.frames,time)?.tokens||[];$('#inspector-subtitle').textContent=`${timeLabel(time)}의 토큰 · ${tokens.length}개`;content.innerHTML=tokens.map(t=>`<button class="token-card ${selected===t.id?'selected-card':''}" data-token-select="${esc(t.id)}"><span class="token-card-heading"><span class="token-dot" style="background:${color(t.color)}"></span>${esc(t.name)}</span><span class="token-memo">${esc(t.memo||'기록된 메모가 없습니다.')}</span>${stats(t)}</button>`).join('')||'<div class="inspector-empty"><p>이 시점에는 토큰이 없습니다.</p></div>';}
 paintIcons();}
function renderTransport(){if(!current)return;$('#seek').value=time;$('#seek').style.setProperty('--progress',100*time/Math.max(1,current.data.duration)+'%');$('#seek').setAttribute('aria-valuetext',timeLabel(time));$('#time-label').innerHTML=`${timeLabel(time)} <span>/ ${timeLabel(current.data.duration)}</span>`;$('.audio-bars').classList.toggle('playing',playing);const active=audioAt(current.data.audio,time).filter(a=>!a.paused);const names=frameAt(current.data.frames,time)?.bgm.filter(b=>b.url).map(b=>b.name||'이름 없는 음원');$('#bgm-name').textContent=active.length?(names?.join(' + ')||`기록된 음원 ${active.length}개`):'재생 중인 BGM 없음';$('#bgm-detail').textContent=active.length?`${active.length} TRACK${active.length>1?'S':''} · ${playing?'PLAYING':'PAUSED'}`:'BGM FILE SYNC';}
function buttonState(){$('#play').innerHTML=ic(playing?'pause':'play');$('#play').setAttribute('aria-label',playing?'일시정지':'재생');paintIcons();}
function syncOriginal(force=false){if(!current||mode!=='original')return;const v=$('#capture-video');if(current.data.video&&url(current.data.video.url)){v.hidden=false;$('#dom-replay').hidden=true;if(!v.src)v.src=url(current.data.video.url);const target=Math.max(0,(time-(current.data.video.start||0))/1000);if(v.readyState>=1&&Math.abs(v.currentTime-target)>.25)v.currentTime=Number.isFinite(v.duration)?Math.min(target,v.duration):target;v.playbackRate=speed;if(playing)v.play().catch(()=>{});else v.pause();}else if(replayer&&force){replayer.setConfig({speed});if(playing)replayer.play(time);else replayer.pause(time);}}
function pause(){playing=false;engine?.sync(time,false,speed,volume);$('#capture-video').pause();replayer?.pause(time);renderTransport();buttonState();}
function seek(next){time=clamp(next,0,current?.data.duration||0);renderScene();renderInspector();renderTransport();engine?.sync(time,playing,speed,volume);syncOriginal(true);}
function toggle(){if(!current)return;if(playing)return pause();if(time>=current.data.duration)seek(0);playing=true;last=performance.now();engine?.sync(time,true,speed,volume);syncOriginal(true);renderTransport();buttonState();}
function setMode(next){if(next==='original'&&!current?.data.video&&current?.data.events.length<2)return;mode=next;$('#board').hidden=mode!=='scene';$('#original').hidden=mode!=='original';$('#scene-tools').hidden=mode!=='scene';$('.scene-label').hidden=mode!=='scene';$('#scene-hint').hidden=mode!=='scene';$('#scene-mode').classList.toggle('selected',mode==='scene');$('#original-mode').classList.toggle('selected',mode==='original');$('#token-tooltip').hidden=true;if(mode==='original')syncOriginal(true);else{$('#capture-video').pause();replayer?.pause(time);renderScene(true);}}
function fitReplay(){if(!replayer)return;const meta=current.data.events.find(e=>e.type===4)?.data||current.data.viewport||{width:1280,height:720};const scale=Math.min($('#stage').clientWidth/meta.width,$('#stage').clientHeight/meta.height);Object.assign($('#dom-replay').style,{width:meta.width+'px',height:meta.height+'px',transform:`translate(-50%,-50%) scale(${scale})`});}
async function load(recording){pause();engine?.stop();replayer?.destroy();replayer=null;current?.release();current=recording;time=0;selected=null;frameKey=null;zoom=1;pan={x:0,y:0};query='';$('#search').value='';$('#dom-replay').innerHTML='';const v=$('#capture-video');v.pause();v.removeAttribute('src');v.load();v.hidden=true;$('#dom-replay').hidden=false;const d=current.data;const errors=new Set();engine=new AudioEngine(d,current.assets,m=>{if(!errors.has(m)){errors.add(m);notify(m);}});$('#session-title').textContent=d.title||'코코포리아 세션';$('#eyebrow').textContent=d.demo?'DEMO SESSION · 예시 기록':'SESSION ARCHIVE';$('#session-meta').textContent=`${new Date(d.startedAt||Date.now()).toLocaleDateString('ko-KR')} · ${timeLabel(d.duration)} · ${d.frames.length.toLocaleString()}개 장면 기록`;$('#sample-badge').textContent=d.demo?'체험용 예시':'불러오기 완료';$('#seek').max=d.duration;$('#duration-label').textContent=timeLabel(d.duration);$('#ruler').innerHTML=Array.from({length:5},(_,i)=>`<span>${timeLabel(d.duration*i/4)}</span>`).join('');$('#event-marks').innerHTML=d.messages.filter(m=>m.t>0).slice(0,3000).map(m=>`<span style="left:${100*m.t/Math.max(1,d.duration)}%"></span>`).join('');$('#original-mode').disabled=!d.video&&d.events.length<2;
 if(d.events.length>=2&&!d.video){try{replayer=new Replayer(sanitizeEvents(d.events,current.assets),{root:$('#dom-replay'),showWarning:false,showDebug:false,mouseTail:false,UNSAFE_replayCanvas:false,skipInactive:false});replayer.pause(0);fitReplay();}catch{notify('원본 화면 복원에 실패했습니다. 자유 보기를 이용하세요.');}}
 setMode(d.frames.length?'scene':'original');page('replay');seek(d.demo?15000:0);notify(d.warnings?.length?`저장 주의 ${d.warnings.length}건 · “보관된 파일 확인”에서 자세히 볼 수 있어요.`:'');}
async function demo(){const d=demoRecording(),blob=demoSound(),link=URL.createObjectURL(blob);d.assets=[{url:'demo:audio',path:'assets/demo',mime:'audio/wav',size:blob.size}];await load({data:d,assets:new Map([['demo:audio',link]]),release:()=>URL.revokeObjectURL(link)});}
async function openFile(file){if(!file)return;notify('기록 파일을 여는 중…');try{await load(await readArchive(file));}catch(e){notify(e.message||'파일을 열지 못했습니다.');}finally{$('#file').value='';}}
async function exportCurrent(){if(!current)return;pause();notify('리플레이 파일을 묶는 중…');try{const d=structuredClone(current.data),blobs=[];d.assets=[];let i=0;for(const [original,local]of current.assets){const blob=await(await fetch(local)).blob(),path='assets/'+i++;d.assets.push({url:original,path,mime:blob.type,size:blob.size});blobs.push({path,blob});}downloadBlob(await makeArchive(d,blobs),(d.title||'CCReplay').replace(/[<>:"/\\|?*]/g,'_')+'.ccreplay');notify('리플레이 파일을 저장했습니다.');}catch(e){notify('저장 실패: '+e.message);}}
function showAssets(){const d=current?.data;if(!d)return;const missing=new Set();for(const f of d.frames)for(const u of [f.room.backgroundUrl,f.room.foregroundUrl,...f.tokens.map(t=>t.iconUrl),...f.items.map(t=>t.imageUrl)])if(u&&!url(u))missing.add(u);for(const a of d.audio)if(a.url&&!url(a.url))missing.add(a.url);dialog('보관된 파일',`<p>음원과 이미지 ${current.assets.size}개가 포함되어 있습니다. 외부 주소를 자동으로 다시 요청하지 않습니다.</p>${missing.size?`<h3>빠진 파일 ${missing.size}개</h3>${[...missing].map(u=>`<div class="missing-file"><span>${esc(u.split('?')[0].slice(-100))}</span><button class="button" data-repair="${esc(u)}">파일 연결</button></div>`).join('')}`:'<div class="success-note">장면과 소리에 필요한 파일이 준비되어 있습니다.</div>'}${d.warnings?.length?`<h3>기록 주의사항</h3><ul class="warning-list">${d.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`:''}<p>파일 연결 후 상단 저장 버튼을 누르면 새 기록 파일에 함께 포함됩니다.</p>`);}
$('#file').onchange=e=>openFile(e.target.files[0]);for(const id of ['open','setup-open'])$('#'+id).onclick=()=>$('#file').click();$('#replay-nav').onclick=()=>page('replay');$('#record-nav').onclick=()=>page('record');$('#load-demo').onclick=demo;$('#play').onclick=toggle;$('#back').onclick=()=>seek(time-10000);$('#forward').onclick=()=>seek(time+10000);$('#seek').oninput=e=>seek(+e.target.value);$('#speed').onchange=e=>{speed=+e.target.value;engine?.sync(time,playing,speed,volume);syncOriginal(true);};$('#volume').oninput=e=>{volume=+e.target.value;engine?.sync(time,playing,speed,volume);};$('#mute').onclick=()=>{volume=volume?0:.7;$('#volume').value=volume;$('#mute').innerHTML=ic(volume?'volume-2':'volume-x');$('#mute').setAttribute('aria-label',volume?'음소거':'음소거 해제');engine?.sync(time,playing,speed,volume);paintIcons();};$('#scene-mode').onclick=()=>setMode('scene');$('#original-mode').onclick=()=>setMode('original');$('#zoom-in').onclick=()=>{zoom=clamp(zoom+.2,.3,4);fitWorld();};$('#zoom-out').onclick=()=>{zoom=clamp(zoom-.2,.3,4);fitWorld();};$('#reset-view').onclick=()=>{zoom=1;pan={x:0,y:0};fitWorld();};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.viewer').requestFullscreen();}catch{notify('전체 화면을 열 수 없습니다.');}};$('#export').onclick=exportCurrent;$('#asset-info').onclick=showAssets;$('#search').oninput=e=>{query=e.target.value.trim();renderInspector();};$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderInspector();});$('#dialog-close').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close();});
$('#help').onclick=()=>dialog('기록 범위와 사용 안내',`<p>자유 보기에서는 토큰 정보를 확인하고 채팅을 검색합니다. 기록 화면에서는 당시 모습과 마우스 움직임을 다시 봅니다.</p><h3>BGM</h3><p>실제로 재생된 음원 파일과 재생 위치·반복·음량을 저장합니다. 다운로드가 실패하면 누락을 표시하며 직접 파일을 연결할 수 있습니다.</p><h3>범위</h3><p>기록 이후의 변화와 시작 당시 브라우저에 로드된 정보가 대상입니다. 과거의 전체 채팅, 타인의 비공개 내용, 숨겨진 카드 앞면은 수집하지 않습니다. 기록자에게 보이는 비공개 채팅은 포함될 수 있습니다.</p><h3>화면 기록</h3><p>3D 주사위·외부 iframe 내부를 보존하려면 화면 보완 녹화를 켜세요. 접근 제한이 있는 자산은 원본 파일 저장에 실패할 수 있습니다. 파일은 1 GB 이하이며, 긴 세션은 나누어 기록하세요.</p><h3>호환성</h3><p>기록기는 Chrome/Edge 116 이상, 코코포리아 1.37.4 내부 구조 기준의 비공식 도구입니다. 서비스 업데이트 시 확인이 필요합니다. 연결 실패와 자산 누락은 파일에 남습니다.</p><p>키보드: Space 재생 · ←/→ 10초 이동 · / 채팅 검색</p>`);
let repairURL;$('#dialog-body').onclick=e=>{const b=e.target.closest('[data-repair]');if(b){repairURL=b.dataset.repair;$('#repair-file').click();}};$('#repair-file').onchange=e=>{const file=e.target.files[0];if(file&&repairURL){const link=URL.createObjectURL(file);current.assets.set(repairURL,link);const prev=current.release;current.release=()=>{prev();URL.revokeObjectURL(link);};engine.stop();engine=new AudioEngine(current.data,current.assets,notify);renderScene(true);$('#dialog').close();notify('파일을 연결했습니다. 저장 버튼으로 새 기록에 포함할 수 있어요.');}e.target.value='';};
$('#inspector-content').onclick=e=>{const m=e.target.closest('[data-message-time]');if(m)return seek(+m.dataset.messageTime);const t=e.target.closest('[data-token-select]');if(t){selected=t.dataset.tokenSelect;renderScene(true);renderInspector();}};$('#world').onclick=e=>{const b=e.target.closest('[data-token]');if(b){selected=b.dataset.token;tab='tokens';renderInspector();renderScene(true);}};
function hover(e){const b=e.target.closest('[data-token]'),tip=$('#token-tooltip');if(!b){tip.hidden=true;return;}const t=frameAt(current.data.frames,time)?.tokens.find(t=>t.id===b.dataset.token);if(!t)return;tip.innerHTML=`<strong>${esc(t.name)}</strong><p>${esc(t.memo)}</p>${stats(t)}`;tip.hidden=false;const r=$('#stage').getBoundingClientRect();tip.style.left=clamp(e.clientX-r.left+16,8,r.width-285)+'px';tip.style.top=clamp(e.clientY-r.top+18,8,r.height-tip.offsetHeight-10)+'px';}
$('#world').onpointermove=hover;$('#world').onpointerleave=()=>$('#token-tooltip').hidden=true;$('#world').onfocusin=e=>{const b=e.target.closest('[data-token]');if(b){const r=b.getBoundingClientRect();hover({target:b,clientX:r.right,clientY:r.top});}};$('#world').onfocusout=()=>$('#token-tooltip').hidden=true;
let drag;$('#board').onpointerdown=e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};$('#board').setPointerCapture(e.pointerId);};$('#board').onpointermove=e=>{if(drag){pan={x:drag.px+e.clientX-drag.x,y:drag.py+e.clientY-drag.y};fitWorld();}};$('#board').onpointerup=()=>drag=null;$('#board').onpointercancel=()=>drag=null;document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||$('#dialog').open)return;if(e.code==='Space'){e.preventDefault();toggle();}if(e.key==='ArrowLeft')seek(time-10000);if(e.key==='ArrowRight')seek(time+10000);if(e.key==='/'){e.preventDefault();tab='chat';renderInspector();$('#search').focus();}});
let depth=0;document.addEventListener('dragenter',e=>{if(!e.dataTransfer?.types.includes('Files'))return;e.preventDefault();depth++;$('#drop-overlay').hidden=false;});document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('dragleave',()=>{if(--depth<=0)$('#drop-overlay').hidden=true;});document.addEventListener('drop',e=>{e.preventDefault();depth=0;$('#drop-overlay').hidden=true;openFile(e.dataTransfer.files[0]);});new ResizeObserver(()=>{fitWorld();fitReplay();}).observe($('#stage'));
function tick(now){if(playing&&current){time=Math.min(current.data.duration,time+(now-last)*speed);if(now-renderStamp>80){renderScene();renderTransport();engine.sync(time,true,speed,volume);syncOriginal();renderStamp=now;}if(now-chatStamp>500){renderInspector();chatStamp=now;}if(time>=current.data.duration)pause();}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
window.addEventListener('pagehide',()=>{engine?.stop();current?.release();});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'replay_seek',description:'열린 리플레이를 지정한 초로 이동합니다.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:0}},required:['seconds'],additionalProperties:false},execute:({seconds})=>{if(!current||!Number.isFinite(seconds)||seconds<0||seconds*1000>current.data.duration)throw Error('기록 범위 안의 시간을 입력하세요.');seek(seconds*1000);return {seconds:time/1000};}},{name:'replay_search_chat',description:'채팅을 검색하고 결과를 화면에 표시합니다.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},execute:({query:q})=>{if(typeof q!=='string'||q.length>200)throw Error('검색어는 200자 이하입니다.');query=q;tab='chat';$('#search').value=q;renderInspector();return {matches:messagesAt(current.data.messages,current.data.duration).filter(m=>(m.name+' '+m.text+' '+m.channelName).toLowerCase().includes(q.toLowerCase())).length};}}]){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:true}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort());}
paintIcons();demo();
