import {createIcons,Play,Pause,FolderOpen,Download,Volume2,VolumeX,Maximize,SkipBack,SkipForward,Search,FileText,Users,Music2,Info,X,Plus,Minus,RotateCcw,Monitor,Layers,ChevronRight,Check,Upload} from 'lucide';
const icons={Play,Pause,FolderOpen,Download,Volume2,VolumeX,Maximize,SkipBack,SkipForward,Search,FileText,Users,Music2,Info,X,Plus,Minus,RotateCcw,Monitor,Layers,ChevronRight,Check,Upload};
export const ic=n=>`<i data-lucide="${n}" aria-hidden="true"></i>`;
export const paintIcons=()=>createIcons({icons,attrs:{'stroke-width':1.6}});
export const $=s=>document.querySelector(s);
export const $$=s=>[...document.querySelectorAll(s)];
export function shell(){$('#app').innerHTML=`<header class="header"><a class="brand" href="/"><span class="brand-mark">${ic('play')}</span>CC REPLAY<span class="beta">BETA</span></a><nav aria-label="주 메뉴"><button class="nav active" id="replay-nav">리플레이</button><button class="nav" id="record-nav">기록하기</button></nav><button class="icon-button" id="help" aria-label="기록 범위와 사용 안내">${ic('info')}</button><button class="button" id="open">${ic('folder-open')}파일 열기</button></header>
<main id="replay-page"><section class="session-heading"><div><div class="eyebrow" id="eyebrow">REPLAY WORKSPACE</div><h1 id="session-title">리플레이를 열어보세요</h1><p id="session-meta"></p></div><div class="heading-actions"><span class="pill" id="sample-badge">예시 세션</span><button class="icon-button" id="export" aria-label="리플레이 파일 저장">${ic('download')}</button></div></section><div id="notice" role="status" hidden></div>
<div class="workspace"><section class="viewer"><div class="viewer-bar"><div class="view-switch" role="group" aria-label="보기 방식"><button id="scene-mode" class="selected">${ic('layers')}자유 보기</button><button id="original-mode">${ic('monitor')}기록 화면</button></div><button class="icon-button" id="fullscreen" aria-label="전체 화면">${ic('maximize')}</button></div>
<div class="stage" id="stage"><div class="scene-label"><span class="scene-number">01</span><span id="scene-name">SCENE</span></div><div class="board-viewport" id="board"><div class="board-world" id="world"></div></div><div id="original" hidden><video id="capture-video" playsinline muted hidden></video><div id="dom-replay"></div></div><div class="scene-tools" id="scene-tools"><button class="icon-button" id="zoom-out" aria-label="축소">${ic('minus')}</button><span id="zoom-label">100%</span><button class="icon-button" id="zoom-in" aria-label="확대">${ic('plus')}</button><button class="icon-button" id="reset-view" aria-label="시점 초기화">${ic('rotate-ccw')}</button></div><div class="scene-hint" id="scene-hint">토큰을 가리켜 정보를 확인하세요</div><div id="token-tooltip" role="tooltip" hidden></div></div>
<div class="timeline"><div class="timeline-top"><span>SESSION TIMELINE</span><span id="duration-label"></span></div><div class="timeline-line"><div id="event-marks"></div><input id="seek" type="range" min="0" max="90000" value="0" step="100" aria-label="재생 위치"></div><div class="ruler" id="ruler"></div></div>
<div class="transport"><div class="transport-group"><button class="icon-button" id="back" aria-label="10초 뒤로">${ic('skip-back')}</button><button class="play" id="play" aria-label="재생">${ic('play')}</button><button class="icon-button" id="forward" aria-label="10초 앞으로">${ic('skip-forward')}</button><span class="time" id="time-label"></span></div><div class="transport-group"><button class="icon-button" id="mute" aria-label="음소거">${ic('volume-2')}</button><input id="volume" class="volume" type="range" min="0" max="1" step=".05" value=".7" aria-label="재생 음량"><select id="speed" aria-label="재생 속도"><option value=".5">0.5×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option><option value="2">2×</option><option value="4">4×</option></select></div></div><div class="audio-strip">${ic('music-2')}<div><span id="bgm-name"></span><small id="bgm-detail">BGM FILE SYNC</small></div><span class="audio-bars"><b></b><b></b><b></b><b></b><b></b></span></div></section>
<aside class="inspector"><div class="inspector-tabs" role="tablist"><button data-tab="chat" class="selected" role="tab" aria-selected="true">${ic('file-text')}채팅<span id="chat-count">0</span></button><button data-tab="tokens" role="tab" aria-selected="false">${ic('users')}토큰<span id="token-count">0</span></button></div><div id="search-wrap" class="search-wrap">${ic('search')}<input id="search" placeholder="채팅 검색" aria-label="전체 기록에서 채팅 검색"><kbd>/</kbd></div><div class="inspector-subtitle" id="inspector-subtitle"></div><div id="inspector-content" role="tabpanel"></div><div class="inspector-footer">메시지를 누르면 그 시점으로 이동합니다</div></aside></div>
<div class="below-workspace"><span>${ic('check')}파일은 브라우저 안에서 재생됩니다</span><button class="text-button" id="asset-info">보관된 파일 확인${ic('chevron-right')}</button></div><footer><span class="footer-brand">CC REPLAY</span><span>다시 펼쳐보는 우리의 이야기.</span><button class="text-button" id="load-demo">예시 리플레이</button></footer></main>
<main id="record-page" hidden><section class="session-heading"><div><div class="eyebrow">CAPTURE YOUR SESSION</div><h1>이야기가 시작되기 전에, 기록 시작.</h1><p>Chrome 또는 Edge에서 코코포리아 방을 열고 기록기를 실행하세요.</p></div><a class="button primary" href="/ccreplay-recorder.zip" download>${ic('download')}기록기 다운로드</a></section><div class="setup-layout"><section class="setup-steps"><article><span class="step-number">01</span><div><h2>기록기 설치</h2><p>다운로드한 ZIP을 폴더에 풀고, Chrome의 확장 프로그램 관리 화면에서 <b>개발자 모드</b>를 켜세요. <b>압축해제된 확장 프로그램을 로드합니다</b>를 누르고 해당 폴더를 선택합니다.</p><code>chrome://extensions</code><small>Edge에서는 edge://extensions</small></div></article><article><span class="step-number">02</span><div><h2>방에서 기록 시작</h2><p>코코포리아 방을 열고 확장 프로그램의 <b>기록 시작</b>을 누르세요. 표시된 장면·토큰, 수신한 채팅, 실제 재생되는 BGM을 기록합니다.</p><a class="button" href="https://ccfolia.com/rooms/3I0wcF7Mh" target="_blank" rel="noopener noreferrer">코코포리아 방 열기${ic('monitor')}</a></div></article><article><span class="step-number">03</span><div><h2>파일 저장, 그리고 리플레이</h2><p><b>기록 종료 → 리플레이 파일 저장</b> 순서로 누른 뒤 이 사이트에서 .ccreplay 파일을 열면 됩니다. 파일을 가진 사람은 저장된 정보를 볼 수 있어요.</p><button class="button" id="setup-open">${ic('folder-open')}리플레이 파일 열기</button></div></article></section><aside class="capture-info"><div class="eyebrow">WHAT GETS SAVED</div><h2>장면은 그대로,<br>정보는 다시 살펴보게.</h2><ul><li>${ic('layers')}배경·패널·토큰과 시간별 위치</li><li>${ic('users')}토큰 이름·메모·공개 상태값</li><li>${ic('file-text')}수신한 채팅·수정·삭제 시점</li><li>${ic('music-2')}음원 파일·재생 위치·음량·반복</li><li>${ic('monitor')}마우스·스크롤·표시된 툴팁</li></ul><p>화면 보완 녹화를 켜면 3D 주사위와 외부 영상의 보이는 모습도 함께 저장합니다. BGM은 음원 파일로 따로 보존합니다.</p><div class="scope-note">기록 이후, 이 브라우저에서 보거나 받은 정보만 남습니다. 기록 전의 움직임과 다른 참가자에게만 보이는 내용은 복원할 수 없습니다. 기록 중 탭을 새로고침하거나 닫으면 종료됩니다.</div><small>코코포리아 1.37.4 구조 기준 · 비공식 기록기</small></aside></div></main>
<input type="file" id="file" accept=".ccreplay,.zip,.json" hidden><input type="file" id="repair-file" hidden><dialog id="dialog"><div class="dialog-header"><h2 id="dialog-title"></h2><button id="dialog-close" class="icon-button" aria-label="닫기">${ic('x')}</button></div><div id="dialog-body"></div></dialog><div id="drop-overlay" hidden>${ic('upload')}리플레이 파일을 놓아주세요</div>`;}
